### PR TITLE
Added AC-Pro functionality and tweaks

### PR DESCRIPTION
**Pull request by kiwi-cam**
Added {mode}{temperature} data config for the air-conditioner accessory
Added allowAutoMode boolean option to config to re-enable Auto mode on air-conditioner
Added returning zero on error reading temperature from file to resolve "updating" hang issue

### CODE REVIEW

**Comment by AlexanderBabel** [comment]
Thanks again! I will make an extra branch in my repo and modify some stuff. After that I will put your changes in the my fork. 

I will do it as early as this or next weekend.

**Comment by Cloudore** [comment]
Amazing work thank you again @kiwi-cam

**Comment by kiwi-cam** [comment]
I've made a few tweaks:
- Improved HeatingCoolingMode code/string handling
- Re-added pseudo-mode support (will replace mode if set in advanced config data)
- Removed allowAutoMode. Instead omitting replaceAutoMode will allow Auto Mode

**Comment by kiwi-cam** [comment]
Added support for Raspberry Pi Wire-1 thermometers (i.e. ds18b20). 
Update air-conditioner config to include (using the device ID):
```
"w1DeviceID":"28-0321544e531ff",
```

**Comment by kiwi-cam** [comment]
I've merged in @RileyEv 's pull request to mine which includes  "pingGrace" for switch accessories. This pauses ping status updates while the device state is changing. This is to stop the devices status changing back to offline while waiting for the device to startup and begin responding to pings.

**Comment by kiwi-cam** [comment]
@RileyEv 's pingGrace functionality is now added to the TV accessory on this Pull Request

**Comment by kiwi-cam** [comment]
Just merged more changes:
 - Improved Broadlink status reliability. Now takes two lost pings before device is marked inactive
 - Fixed Aircon status changes. Only sends mode on a mode change now fixed temperature resets in iOS13
 - Improved logging

**Pull request merged**
