### PR TITLE
Documentation Updates

### PR DESCRIPTION
**Pull request by kiwi-cam**
I've added new features to the README.md file to build upon the existing documentation.

### CODE REVIEW

**Comment by AlexanderBabel** [comment]
Hey, I added you as a direct contributor for this project therefore you can work directly now on this project. But keep in mind that many users are using this plugin and they are expecting that the plugin will work with the same configuration as before.

Also if you are ready for a new release on npmjs just write me, I will publish then the newest master version. If you want the permissions to publish updates on npmjs by yourself, please let me know.

Thanks again for your support and work on this fork!

**Comment by kiwi-cam** [comment]
Thanks @AlexanderBabel. I usually run my own homebridge off my github code before creating the pull request. It's not perfect being a single test user but I do my best to test what I can. I was probably a little more relaxed about it knowing you'd take a look before merging... so maybe I'll run for another day before I do this merge.

I haven't got my head around npmjs yet. Probably best for you to keep managing that part.

**Comment by kiwi-cam** [comment]
I'll re-create to resolve conflicts

**Comment by kiwi-cam** [comment]
@AlexanderBabel I've been running on this from home pretty happily since a couple of bug fixes. It's probably a good time for a npmjs publish.

**Comment by AlexanderBabel** [comment]
Alright I’ll do it as early as this Friday. Currently I have no access to a Computer. Therefore it will be Friday. Feel free to still work and push some updates. And thanks again for work time and effort in this project!

**Pull request closed without merging**
